### ISSUE TITLE
Paper about this inpainting code

### ISSUE THREAD

**Issue by Caiofontoura** [cantarinigiorgio/Image-Inpainting#1]
My name is Caio Fontoura. I am a PhD student at Unesp in Brazil. Has this inpainting code been published anywhere?

**Comment by cantarinigiorgio** [comment]
Hi, this is an implementation of the algorithm proposed in 'Region Filling and Object Removal by Exemplar-Based Image Inpainting' by A. Criminisi, P. Perez, and K. Toyama (you can find it at the link https://www.irisa.fr/vista/Papers/2004_ip_criminisi.pdf).
This is not the official implementation by the authors (I don't think they provide their implementation), but it is a re-implementation written in MATLAB.

**Comment by Caiofontoura** [comment]
Hello, Good Afternoon!

Thank you for your return.

Sincerely,

Caio Fontoura Júnior.

Em seg., 19 de abr. de 2021 às 10:24, cantarinigiorgio <
***@***.***> escreveu:
